apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: samediggi-no

resources:
  - ../../../base
  - onepassword.yaml

#commonLabels:
#  app.kubernetes.io/instance: adapter-faks_samediggi-no
#  fintlabs.no/org-id: samediggi.no

patches:

  - target:
      kind: Deployment
      name: adapter-faks
    path: deployment.yaml

  - target:
      kind: Deployment
      name: adapter-faks
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: "adapter-faks-samediggi"
      - op: replace
        path: "/spec/selector/matchLabels/app"
        value: "adapter-faks-samediggi"
      - op: replace
        path: "/spec/template/metadata/labels/app"
        value: "adapter-faks-samediggi"
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: "adapter-faks-samediggi"