apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samediggi-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-faks_samediggi-no
  fintlabs.no/org-id: samediggi.no

patches:

  - target:
      kind: Deployment
      name: adapter-arkiv-faks
    path: deployment.yaml
