apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-arkiv-faks
  namespace: bya-oslo-kommune-no
spec:
  template:
    spec:
      containers:
        - name: adapter-arkiv-faks
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "3Gi"
          envFrom:
            - secretRef:
                name: faks-adapter-onepassword
          env:
            - { name: TZ, value: Europe/Oslo }
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xmx3G -verbose:gc
                -XX:+ExitOnOutOfMemoryError
                -Dfile.encoding=UTF-8
            - { name: springfox.title, value: "SvarUt (Faks) Adapter for Byantikvaren Oslo kommune" }
            - { name: security.basic.enabled, value: "false" }

            - { name: fint.adapter.organizations, value: bya.oslo.kommune.no }
            - { name: fint.adapter.reject-unknown-events, value: 'false' }

            - { name: fint.case.defaults.tilskuddfartoy.title.cases, value: 'Tilskudd - ${kallesignal} - ${fartoyNavn} - ${kulturminneId} - ${soknadsnummer.identifikatorverdi} - ${tittel}' }
            - { name: fint.case.defaults.tilskuddfartoy.field.fartoy, value: '${kallesignal} ${fartoyNavn}' }
            - { name: fint.case.defaults.tilskuddfartoy.field.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
            - { name: fint.case.defaults.tilskuddfartoy.field.kulturminneid, value: '${kulturminneId}' }
            - { name: fint.case.defaults.tilskuddfredabygningprivateie.title.cases, value: 'Tilskudd - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${bygningsnavn} - ${kulturminneId} - ${soknadsnummer.identifikatorverdi} - ${tittel}' }
            - { name: fint.case.defaults.tilskuddfredabygningprivateie.field.matrikkel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
            - { name: fint.case.defaults.tilskuddfredabygningprivateie.field.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
            - { name: fint.case.defaults.tilskuddfredabygningprivateie.field.kulturminneid, value: '${kulturminneId}' }
            - { name: fint.case.defaults.dispensasjonautomatiskfredakulturminne.title.cases, value: 'Tilskudd - ${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer} - ${kulturminneId} - ${soknadsnummer.identifikatorverdi} - ${tittel}' }
            - { name: fint.case.defaults.dispensasjonautomatiskfredakulturminne.field.matrikkel, value: '${matrikkelnummer.gardsnummer}/${matrikkelnummer.bruksnummer}' }
            - { name: fint.case.defaults.dispensasjonautomatiskfredakulturminne.field.soknadsnummer, value: '${soknadsnummer.identifikatorverdi}' }
            - { name: fint.case.defaults.dispensasjonautomatiskfredakulturminne.field.kulturminneid, value: '${kulturminneId}' }

            - { name: fint.internal-files.type, value: 'BLOB' }

            - { name: fint.adapter.endpoints.providers.kodeverk, value: http://provider-arkiv-kodeverk.default:8080/arkiv/kodeverk/provider }
            - { name: fint.adapter.endpoints.providers.noark, value: http://provider-arkiv-noark.default:8080/arkiv/noark/provider }
            - { name: fint.adapter.endpoints.providers.kulturminne, value: http://provider-arkiv-kulturminnevern.default:8080/arkiv/kulturminnevern/provider }
