apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bya-oslo-kommune-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-faks_bya-oslo-kommune-no
  fintlabs.no/org-id: bya.oslo.kommune.no

patches:

  - target:
      kind: Deployment
      name: adapter-faks
    path: deployment.yaml
