apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-arkiv-faks
  namespace: bym-oslo-kommune-no
spec:
  template:
    spec:
      volumes:
        - name: certificate
          secret:
            secretName: faks-adapter-onepassword
      containers:
        - name: adapter-arkiv-faks
          volumeMounts:
            - name: certificate
              mountPath: /secrets
          envFrom:
            - secretRef:
                name: faks-adapter-onepassword
          env:
            - {name: springfox.title, value: "SvarUt (Faks) Adapter for Oslo kommune bymiljøetaten"}
            - {name: fint.adapter.organizations, value: bym.oslo.kommune.no}
            - {name: fint.adapter.reject-unknown-events, value: 'false'}

            - {name: fint.case.defaults.soknaddrosjeloyve.title.cases, value: 'Drosjeløyvesøknad: ${organisasjonsnavn}'}

            - {name: fint.adapter.endpoints.providers.kodeverk, value: https://api.felleskomponent.no/arkiv/kodeverk/provider}
            - {name: fint.adapter.endpoints.providers.noark, value: https://api.felleskomponent.no/arkiv/noark/provider}
            - {name: fint.adapter.endpoints.providers.samferdsel, value: https://api.felleskomponent.no/arkiv/samferdsel/provider}

            - {name: logging.level.no.fint, value: "trace"}
