apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-faks
spec:
  template:
    spec:
      volumes:
        - name: certificate
          secret:
            secretName: faks-adapter-bym-oslo
      containers:
        - name: faks-adapter
          image: fintlabsacr.azurecr.io/fint-faks-adapter:2023-07-04-f696933
          envFrom:
            - secretRef:
                name: faks-adapter-bym-oslo
          env:
            - {name: springfox.title, value: "SvarUt (Faks) Adapter for Oslo kommune bymiljøetaten"}
            - {name: fint.adapter.organizations, value: bym.oslo.kommune.no}
            - {name: fint.adapter.reject-unknown-events, value: 'false'}
            - {name: fint.case.defaults.soknaddrosjeloyve.title.cases, value: 'Drosjeløyvesøknad: ${organisasjonsnavn}'}
            - {name: spring.data.mongodb.database, value: 'svarut-faks'}
            - {name: fint.adapter.endpoints.providers.kodeverk, value: https://api.felleskomponent.no/arkiv/kodeverk/provider}
            - {name: fint.adapter.endpoints.providers.noark, value: https://api.felleskomponent.no/arkiv/noark/provider}
            - {name: fint.adapter.endpoints.providers.samferdsel, value: https://api.felleskomponent.no/arkiv/samferdsel/provider}
            - {name: logging.level.no.fint, value: "trace"}
