apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bym-oslo-kommune-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-faks_bym-oslo-kommune-no
  fintlabs.no/org-id: bym.oslo.kommune.no

patches:

  - target:
      kind: Deployment
      name: adapter-arkiv-faks
    path: deployment.yaml
